name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-15"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTcwY2M0NzUtNmQ3Yy00NGRmLWE5ZTktNjEzNTE1MGZhOGQ0IiwidGVuYW50X2lkIjoiMGRhMjU1OWU2ZTA3NGVmNGI5MzQ0ZDY4YjM0NGZiN2Y3YzJjMjgyZDc4ZTUyZmFmNTdlZDFhOGYxOGRmMDg1YiIsImludGVybmFsX3NlY3JldCI6IjhmM2Q1MGY3LWUyMmYtNGQ5NC1iMTI3LWZhYzRkM2M4ODcwZiJ9.FKl3QIl8ooZR2wI3D9pcOeZXT_F3y-5GPhUtr_ID2uE"DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTcwY2M0NzUtNmQ3Yy00NGRmLWE5ZTktNjEzNTE1MGZhOGQ0IiwidGVuYW50X2lkIjoiMGRhMjU1OWU2ZTA3NGVmNGI5MzQ0ZDY4YjM0NGZiN2Y3YzJjMjgyZDc4ZTUyZmFmNTdlZDFhOGYxOGRmMDg1YiIsImludGVybmFsX3NlY3JldCI6IjhmM2Q1MGY3LWUyMmYtNGQ5NC1iMTI3LWZhYzRkM2M4ODcwZiJ9.FKl3QIl8ooZR2wI3D9pcOeZXT_F3y-5GPhUtr_ID2uE"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1